### PR TITLE
fix(@schematics/angular): Restrict some schematics to type of applica…

### LINKED ISSUE #789: Restrict usage of some schematics to project type of "application"
- app shell
- pwa
- service worker
- universal

### PR DESCRIPTION
**Pull request by Brocco**
…tion

fixes #789

### CODE REVIEW

File: packages/schematics/angular/universal/index.ts [hunk 1]
```diff
@@ -205,6 +205,9 @@ function getTsConfigOutDir(host: Tree, architect: experimental.workspace.Workspa
 export default function (options: UniversalOptions): Rule {
   return (host: Tree, context: SchematicContext) => {
     const clientProject = getClientProject(host, options);
+    if (clientProject.projectType !== 'application') {
+      throw new SchematicsException(`App shell requires a project type of "application".`);
```
Comment (clydin) [inline packages/schematics/angular/universal/index.ts]: `Universal requires`?

File: packages/schematics/angular/service-worker/index.ts [hunk 2]
```diff
@@ -232,6 +232,9 @@ export default function (options: ServiceWorkerOptions): Rule {
     if (!project) {
       throw new SchematicsException(`Invalid project name (${options.project})`);
     }
+    if (project.projectType !== 'application') {
+      throw new SchematicsException(`App shell requires a project type of "application".`);
```
Comment (clydin) [inline packages/schematics/angular/service-worker/index.ts]: `service worker requires`?
