### PR TITLE
fix(@angular-devkit/build-optimizer): only prefix top-level functions…

### LINKED ISSUE #51: ngo is removing rxjs add operators
Using:
```
@angular/cli: 1.3.0-rc.1
node: 8.1.3
os: linux x64
@angular/animations: 4.3.1
@angular/cli: 1.3.0-rc.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/compiler-cli: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/service-worker: 1.0.0-beta.16
```

I have `import 'rxjs/add/operator/filter';` at the top of my app.component.ts file.

**Expected Behavior:**
When I use .filter on an observable, I expect the call to succeed

**Observed Behavior**
The filter method is missing from the prototype of Observable.

**Other Background**
In the source code generated with `ng build -prod -bo`, the import is being marked as pure.

```
        /*@__PURE__*/
        __webpack_require__("gbhw");
```

### LINKED ISSUE #52: ngo is removing console logs
Using:
```
@angular/cli: 1.3.0-rc.1
node: 8.1.3
os: linux x64
@angular/animations: 4.3.1
@angular/cli: 1.3.0-rc.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/compiler-cli: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/service-worker: 1.0.0-beta.16
```

I have `console.log("Can anyone hear me?!");;` at the top of my app.component.ts file, outside the scope of my component.

**Expected Behavior:**
When the application runs, the console.log message is printed.

**Observed Behavior**
The console log is not running

**Other Background**
In the source code generated with `ng build -prod -bo`, the import is being marked as pure.

```
 /*@__PURE__*/
        console.log("Can anyone hear me?!");
```

### PR DESCRIPTION
**Pull request by filipesilva**
… in Angular packages

Fix #51
Fix #52

### CODE REVIEW

File: packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts [hunk 1]
```diff
@@ -50,15 +51,22 @@ export function buildOptimizer(options: BuildOptimizerOptions):
...
     getTransforms.push(...[
+      // getPrefixFunctionsTransformer is rather dangerous.
+      // It will mark both `require()` calls and `console.log(stuff)` as pure.
+      // We only apply it to @angular/* packages, since we know they are safe.
       getPrefixFunctionsTransformer,
       getScrubFileTransformer,
       getFoldFileTransformer,
     ]);
+  } else if (hasDecorators.test(content) || hasCtorParameters.test(content)) {
+    getTransforms.push(...[
```
Comment (hansl) [inline packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts]: You can just 

```typescript
    getTransforms.push(getScrubFileTransformer, getFoldFileTransformer);
```

Push accepts a variable number of arguments.

Comment (filipesilva) [inline packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts]: Fixed.

Comment (gkalpak) [inline packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts]: Boooriiing 😫

`...[a, b]` is so much cooler 😛
